name: COMP597-project
channels:
  - defaults
  - codecarbon
  - conda-forge
dependencies:
  - python=3.14
  - conda=25.9
  - libmamba-solver
  - datasets>=3.5.0
  - transformers>=4.57.1
  - torch=2.9.1
  - codecarbon>=3.0.0
  - numpy
  - pandas
  - tqdm
